# docker run -it --name trails-db pathless-db
# docker run -it --name trails-node -p 1000:1000

services:
    custom-postgres:
        container_name: postgres-db
        build:
            context: ./database

    custom-node:
        container_name: node-server
        build:
            context: .
        ports:
            - '80:1000'
        depends_on:
            - custom-postgres
